const types = {
    authMessage: '(auth) message',  
    authStatus: '(auth) status',
    authLogin : '(auth) login',
    authError : '(auth) authError',
    authErrorToken : '(auth) authErrorToken',
    authProfile : "(auth) authProfile",
    userList: '(user) userList',
    userProfile: '(user) userProfile',
    userCover: '(user) userCover',
    userUpdatedValueProfile: '(user) userUpdatedValueProfile',
    userUpdatedValueCover: '(user) userUpdatedValueCover',
    userUpdatedValuesReset: '(user) userUpdatedValuesReset',
    solicitudOne: '(user) solicitudOne',
    userGetList: '(user) userGetList',
    publicacionUpdate: "(publicacion) publicacionUpdate",
    publicacionesProfile: "(publicacion) publicacionesProfile",
    publicacionesLOading: "(publicacion) publicacionesLOading",
    publicacionesCreated: "(publicacion) publicacionesCreated",
    publicacionesUpdated: "(publicacion) publicacionesUpdated",
    publicacionBtn: "(publicacion) publicacionBtn",
    publicacionBtnOcultar: "(publicacion) publicacionBtnOcultar",
    publicacionPaginationGet: "(publicacion) publicacionPaginationGet",
    ResetearValoresPreterminados: "(publicacion) ResetearValoresPreterminados",
    reactValues: "(react) reactValues",
    historyBackTrue: "(react) historyBackTrue",
    historyBackFalse: "(react) historyBackFalse",
    reactValuesReset: "(react) reactValuesReset",
    reactmostrarPubs: "(react) reactmostrarPubs",
    reactValuesUpdated: "(react) reactValuesUpdated",
    usersGetValues : "(users) usersGetValues",
    usersResetValues : "(users) usersResetValues",
    usersUpdatedValues : "(users) usersUpdatedValues",
    userOneGet : "(users) userOneGet",
    userOneDelete : "(users) userOneDelete",
    notificationSet : "(notification) notificationSet",
    notificationRemove : "(notification) notificationRemove",
    notificationCountClear : "(notification) notificationCountClear",
    notificationGetAll : "(notification) notificationGetAll",
    notificationUpdateAll : "(notification) notificationUpdateAll",
    // reactValuesReset: "(react) reactValuesReset",

}

export default types;